version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    hostname: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      registry-network:
        ipv4_address: 172.22.0.2

  registry:
    image: registry:2
    container_name: registry
    environment:
      REGISTRY_STORAGE: s3
      REGISTRY_STORAGE_S3_ACCESSKEY: minioadmin
      REGISTRY_STORAGE_S3_SECRETKEY: minioadmin
      REGISTRY_STORAGE_S3_BUCKET: registry
      REGISTRY_STORAGE_S3_REGION: us-east-1
      REGISTRY_STORAGE_S3_REGIONENDPOINT: http://172.22.0.2:9000
      REGISTRY_STORAGE_S3_SECURE: "false"
      REGISTRY_STORAGE_S3_FORCEPATHSTYLE: "true"
    depends_on:
      - minio
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./registry/config.yml:/etc/docker/registry/config.yml
      - ./registry/certs:/certs
    networks:
      - registry-network

networks:
  registry-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24
          gateway: 172.22.0.1
